before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y ffmpeg; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg --without-gpl; fi

language: node_js
node_js:
  - 8
os:
  - linux
  - osx
