before_install:
  - brew install ffmpeg --without-gpl --without-x264 --without-xvid
  - brew link ffmpeg

language: node_js
node_js:
  - 8
os:
  - osx

cache:
  directories:
    - node_modules
    - /usr/local/Cellar/ffmpeg
