before_install:
  - brew install ffmpeg --without-gpl --without-x264 --without-xvid

language: node_js
node_js:
  - 8
os:
  - osx

cache:
  directories:
    - node_modules
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar/ffmpeg
