before_install:
  - brew install ffmpeg --without-gpl --without-x264 --without-xvid
  - brew link nasm pkg-config texi2html lame ffmpeg

language: node_js
node_js:
  - 8
os:
  - osx

branches:
  only:
    - staging
    - trying

cache:
  directories:
    - node_modules
    - /usr/local/Cellar/nasm
    - /usr/local/Cellar/pkg-config
    - /usr/local/Cellar/texi2html
    - /usr/local/Cellar/lame
    - /usr/local/Cellar/ffmpeg
